#!/bin/bash

# Define the code to be added
code_to_add="
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

PS1='\${debian_chroot:+(\$debian_chroot)}\\[\033[01;32m\\]\u@\h\\[\033[00m\\]:\\[\033[01;34m\\]\w\\[\033[00m\\]\\[\033[33m\\]\$(parse_git_branch)\\[\033[00m\\]\\$ '
"

# Get the user's home directory
home_dir=$(eval echo ~$USER)

# Append the code to the .bashrc file
echo "$code_to_add" >> "$home_dir/.bashrc"

echo "git branch display functionality added to $home_dir/.bashrc"
